buyer_status_graph:
  requested:
  approved:
    - signingstarted
  signingstarted:
  buyersigned:
  sellersigned:
  downpaid:
  fullypaid:
  denied:

seller_status_graph:
  requested:
    - denied
    - approved
  approved:
    - requested
  signingstarted:
  buyersigned:
  sellersigned:
  downpaid:
  fullypaid:
  denied:
    - requested

status:
  - requested
  - approved
  - signingstarted
  - buyersigned
  - sellersigned
  - downpaid
  - fullypaid
  - denied

groups:
  denied:
    - denied
  pendingApproval:
    - requested
    - approved
  pendingSignature:
    - signingstarted
    - buyersigned
    - sellersigned
  onGoing:
    - downpaid
  done:
    - fullypaid

destination-pov-and-status-to-group:
  seller:
    requested: pendingApproval
    buyersigned: pendingSignature
    downpaid: onGoing
    fullypaid: done
  buyer:
    denied: denied
    approved: pendingApproval
    sellersigned: pendingSignature
    requested: pendingApproval
