secret-token: b4e171c1-8b90-4c0a-8c24-87f3a1f12af0

contracts-templates-ids:
  iac: 3bd80763-6fd9-4b28-91e7-f826a648962f

esignatures_contracts_api_url: https://esignatures.io/api/contracts
signature-request-links-expiration-delay-hours: 168 # one week
signature_request_delivery_method: embedded
signed_document_delivery_method: email
required_identification_methods:
  - sms