verification_file_max_size: 10485760 #10Mo
photo_max_size: 4194304 #4Mo
photo_low_res_width: 720 #pixels

allowed_verification_file_content_types:
  - image/jpeg
  - image/jpg
  - image/png
  - application/pdf

allowed_photos_content_types:
  - image/jpeg
  - image/jpg
  - image/png

cover_types:
  - lib
  - hand

onsite_cover_types:
  - lib
  - hand

remote_cover_types: []

balance_payment_conditions:
  - covered
  - covered_1_10
  - living_foal
  - living_foal_48

advance_min_percentage_value: 15
advance_max_percentage_value: 50

available_std_tests:
  - metrite
  - arterite
  - anemie

minimum_std_test_oldness: 1
maximum_std_test_oldness: 180

available_vaccines:
  - rhino
  - grippe
  - tetanos

profile_statuses:
  - to_be_validated
  - hidden
  - visible

cover_minimum_price: 10
