c_saillies_max_size: 10000000 #10Mo
photo_max_size: 4000000 #4Mo

cover_types:
  - lib
  - hand
  - iai
  - iart
  - iac

cover_types_for_which_cover_place_has_to_be_provided:
  - iart
  - iac

balance_payment_conditions:
  - covered
  - covered_1_10
  - living_foal
  - living_foal_48

advance_min_percentage_value: 15
advance_max_percentage_value: 50

breeds:
  - AQPS
  - Anglo-Arabe
  - Arabe
  - Ardennais
  - Auxois
  - Barbe
  - Baudet du Poitou
  - Boulonnais
  - Breton
  - Camargue
  - Cheval Castillonnais
  - Cheval Corse
  - Cheval Miniature Français
  - Cheval de Dressage Français
  - Cheval de Mérens
  - Cheval de Race Auvergne
  - Cheval de Sport Anglo-Normand
  - Cheval du Vercors de Barraquand
  - Cob Normand
  - Comtois
  - Connemara
  - Criollo
  - Crème
  - Dartmoor
  - Fjord
  - Franches-Montagnes
  - Haflinger
  - Henson
  - Highland
  - Irish Cob
  - Islandais
  - Landais
  - Lipizzan
  - Lusitanien
  - New-Forest
  - Percheron
  - Poitevin Mulassier
  - Poney Français de Selle
  - Pottok
  - Pur Sang Anglais
  - Selle Français
  - Shagya
  - Shetland
  - Trait du Nord
  - Trakehner
  - Trotteur Français
  - Welsh
  - Âne Bourbonnais
  - Âne Corse
  - Âne Grand Noir du Berry
  - Âne Normand
  - Âne de Provence
  - Âne des Pyrénées
  - Âne du Cotentin