verification_file_max_size: 10000000 #10Mo
photo_max_size: 4000000 #4Mo
photo_low_res_width: 720 #pixels

cover_types:
  - lib
  - hand
  - iai
  - iart
  - iac

onsite_cover_types:
  - lib
  - hand
  - iai

remote_cover_types:
  - iart
  - iac

balance_payment_conditions:
  - covered
  - covered_1_10
  - living_foal
  - living_foal_48

advance_min_percentage_value: 15
advance_max_percentage_value: 50

available_std_tests:
  - metrite
  - arterite
  - anemie

minimum_std_test_oldness: 1
maximum_std_test_oldness: 180

available_vaccines:
  - rhino
  - grippe
  - tetanos

profile_statuses:
  - to_be_validated
  - hidden
  - visible