logo_filename: logo-black.png
declared_sender_email: noreply@lerepairedeletalon.com
service_email: postmaster@lerepairedeletalon.com
password: "!*QcQb*_AQ2Z2FkpCZFP"
email_verification_route: /email-verification
password_update_page: /password-update
smtp_server_name: ssl0.ovh.net
smtp_server_port_out: 587
