status:
  - offered
  - approved
  - signingstarted
  - buyersigned
  - sellersigned
  - downpaid
  - fullypaid

groups:
  pendingApproval:
    - offered
    - approved
  pendingSignature:
    - signingstarted
    - buyersigned
    - sellersigned
  onGoing:
    - downpaid
  done:
    - fullypaid
