fees_coeff: 0.08

api_key: sk_test_51OvTQH2M9MS38ftinIjvSgCfFzcnTgIUPgYoTXYDlwcx2OTt2JPfZzVZHPMEK9ho1CLpDfdRV5GWTLZeJh3iSnr700QZJ1bfIT
accounts_endpoint_secret: whsec_f6LnqrvkBll72TwohQbEUDcryMA80qWn
checkout_endpoint_secret: whsec_uqWRJRyw3oo2ujBfjTvWHMiMNLpqtv9u
